# Generated by Django 3.1 on 2020-11-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabLabUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_uuid', models.CharField(max_length=14, unique=True, verbose_name='RFID UUID')),
                ('username', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_login', models.BooleanField(default=False, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='FilamentUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filament_name', models.CharField(max_length=14, unique=True)),
                ('filament_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filament_weight', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_printer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lifespan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintainence_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UsageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=14)),
                ('file_name', models.CharField(max_length=100)),
                ('print_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_stamp', models.CharField(max_length=20, unique=True)),
                ('print_status', models.CharField(max_length=14)),
                ('printer_name', models.CharField(max_length=14)),
                ('filament_name', models.CharField(max_length=14)),
                ('filament_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filament_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filament_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filament_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operating_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('printer_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
