# Generated by Django 3.1 on 2020-11-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabLabUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_uuid', models.CharField(max_length=14, unique=True, verbose_name='RFID UUID')),
                ('username', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_login', models.BooleanField(default=False, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filament_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filament_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('model_weight', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_printer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lifespan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintainence_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filament_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filament_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('model_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('power_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_printer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lifespan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintainence_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.CharField(max_length=14)),
                ('file_name', models.CharField(max_length=50)),
                ('print_time', models.DecimalField(decimal_places=3, max_digits=15)),
                ('time_stamp', models.BigIntegerField()),
                ('print_status', models.CharField(max_length=14)),
                ('printer_name', models.CharField(max_length=14)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
