# Generated by Django 3.1 on 2020-11-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagedata',
            name='filament_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
