# Generated by Django 3.1 on 2020-11-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0003_auto_20201127_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagedata',
            name='filament_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
