# Generated by Django 3.1 on 2020-11-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0004_auto_20201127_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagedata',
            name='print_time',
            field=models.CharField(max_length=10),
        ),
    ]
