# Generated by Django 3.1 on 2020-12-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0005_auto_20201128_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=14, unique=True)),
                ('service_interval', models.PositiveSmallIntegerField()),
                ('total_hours', models.PositiveSmallIntegerField()),
                ('remaining_hours', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='printerusage',
            name='lifespan',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
