# Generated by Django 3.1 on 2020-12-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0006_auto_20201202_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='remaining_hours',
            new_name='print_hours',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='total_hours',
        ),
    ]
