# Generated by Django 3.1 on 2020-12-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0007_auto_20201203_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fablabuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='fablabuser',
            name='is_login',
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='last_access_date',
            field=models.CharField(default='', max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='printer_name',
            field=models.CharField(default='EOS', max_length=14),
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='status',
            field=models.CharField(default='Inactive', max_length=14),
        ),
    ]
