# Generated by Django 3.1 on 2020-12-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0010_auto_20201205_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fablabuser',
            name='last_access_date',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='fablabuser',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
