# Generated by Django 3.1 on 2020-12-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0011_auto_20201206_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fablabuser',
            name='last_access_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
