# Generated by Django 3.1 on 2020-12-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0012_auto_20201208_2308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilamentUsage',
            new_name='Filament',
        ),
        migrations.RenameModel(
            old_name='OperatingUsage',
            new_name='Operating',
        ),
        migrations.RenameModel(
            old_name='PrinterUsage',
            new_name='Printer',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='print_hours',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_interval',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
