# Generated by Django 3.1 on 2020-12-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0013_auto_20201210_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='print_hours',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_interval',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
