# Generated by Django 3.1 on 2020-12-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0015_auto_20201212_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=14, unique=True)),
                ('last_access_date', models.CharField(blank=True, default='', max_length=20)),
                ('print_hours', models.PositiveSmallIntegerField()),
                ('filament_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operating_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('printer_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
