# Generated by Django 3.1 on 2021-02-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manager', '0017_auto_20201213_2104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FabLabUser',
            new_name='FabLabPrinter',
        ),
    ]
